# NumPy Tutorial

This notebook demonstrates the basic functionalities of NumPy, a fundamental package for scientific computing in Python.

In [1]:
import numpy as np

## 1. Creating Arrays

In [2]:
# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1d)

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:")
print(arr2d)

# Create an array of zeros
zeros = np.zeros((3, 3))
print("\nArray of zeros:")
print(zeros)

# Create an array of ones
ones = np.ones((2, 2))
print("\nArray of ones:")
print(ones)

# Create an identity matrix
identity = np.eye(3)
print("\nIdentity matrix:")
print(identity)

# Create an array with a range of values
range_arr = np.arange(0, 10, 2)
print("\nArray with range:", range_arr)

1D array: [1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]]

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
[[1. 1.]
 [1. 1.]]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array with range: [0 2 4 6 8]


## 2. Array Operations

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Element-wise multiplication
print("Multiplication:", a * b)

# Dot product
print("Dot product:", np.dot(a, b))

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("\nMatrix multiplication:")
print(np.matmul(A, B))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot product: 32

Matrix multiplication:
[[19 22]
 [43 50]]


## 3. Array Indexing and Slicing

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:")
print(arr)

# Indexing
print("\nElement at index [1, 2]:", arr[1, 2])

# Slicing
print("\nFirst two rows, all columns:")
print(arr[:2, :])

print("\nAll rows, last two columns:")
print(arr[:, -2:])

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at index [1, 2]: 7

First two rows, all columns:
[[1 2 3 4]
 [5 6 7 8]]

All rows, last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]


## 4. Broadcasting

In [5]:
# Broadcasting allows NumPy to work with arrays of different shapes
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("Array a:")
print(a)
print("\nArray b:", b)

print("\na + b (broadcasting):")
print(a + b)

Array a:
[[1 2 3]
 [4 5 6]]

Array b: [10 20 30]

a + b (broadcasting):
[[11 22 33]
 [14 25 36]]


## 5. Array Functions

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(arr)

print("\nSum of all elements:", np.sum(arr))
print("Mean of all elements:", np.mean(arr))
print("Standard deviation:", np.std(arr))
print("Minimum value:", np.min(arr))
print("Maximum value:", np.max(arr))

print("\nSum along columns:", np.sum(arr, axis=0))
print("Sum along rows:", np.sum(arr, axis=1))

Original array:
[[1 2 3]
 [4 5 6]]

Sum of all elements: 21
Mean of all elements: 3.5
Standard deviation: 1.707825127659933
Minimum value: 1
Maximum value: 6

Sum along columns: [5 7 9]
Sum along rows: [ 6 15]


## 6. Reshaping Arrays

In [7]:
arr = np.arange(12)
print("Original array:", arr)

# Reshape to 2D array
arr_2d = arr.reshape(3, 4)
print("\nReshaped to 2D:")
print(arr_2d)

# Flatten array
print("\nFlattened array:", arr_2d.flatten())

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 2D:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 7. Random Number Generation

In [8]:
# Generate random numbers
print("Random float between 0 and 1:", np.random.random())
print("\nArray of random integers between 0 and 10:")
print(np.random.randint(0, 10, size=(3, 3)))

# Set random seed for reproducibility
np.random.seed(42)
print("\nRandom numbers with seed:")
print(np.random.rand(5))

Random float between 0 and 1: 0.14603441992683797

Array of random integers between 0 and 10:
[[3 4 5]
 [9 2 0]
 [9 3 7]]

Random numbers with seed:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
